scss_files: '_scss/*.scss'
linters:
  Comment:
    enabled: false
  IdSelector:
    enabled: false
  PropertySortOrder:
    enabled: false
  StringQuotes:
    enabled: false
  UrlFormat:
    enabled: false
