permalink: /:year/:month/:title.html
safe: true
markdown: kramdown
highlighter: rouge
syntax-highlighting:
  enabled: true
paginate: 2
sass:
  style: compressed
excerpt_separator: <!--more-->
# Site Settings
title: La Grieta
description: Una película de Irene Yagüe Herrero y Alberto García Ortiz
author: Irene Yagüe Herrero y Alberto García Ortiz
url: "http://lagrieta.es"
email: "lagrieta.pelicula@gmail.com"
plugins:
  - jekyll-twitter-plugin
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
